export const seedData = [
  {
    name: "La Martiniere College",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Telangana",
    pinCode: "537922",
    address: "Hazratganj",
    feesMin: 42195,
    feesMax: 183010,
    phone: "+917176599221",
    email: "la-martiniere-college9640@example.com",
    website: "https://uniformapp.in/la-martiniere-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/La_Martiniere_College_Lucknow_image1_7.jpeg",
  },
  {
    name: "Jagran Public School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "394262",
    address: "Gomti Nagar",
    feesMin: 27921,
    feesMax: 70956,
    phone: "+919251666594",
    email: "jagran-public-school109@example.com",
    website: "https://uniformapp.in/jagran-public-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Jagran_Public_School_Lucknow_image1_13.jpeg",
  },
  {
    name: "Seth Anandram Jaipuria",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "867342",
    address: "Gomti Nagar",
    feesMin: 24059,
    feesMax: 117815,
    phone: "+917012189246",
    email: "seth-anandram-jaipuria2842@example.com",
    website: "https://uniformapp.in/seth-anandram-jaipuria-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Seth_Anandram_Jaipuria_Lucknow_image1_18.jpeg",
  },
  {
    name: "Lucknow Public School Vinamra Khand",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "633305",
    address: "Gomti Nagar",
    feesMin: 41641,
    feesMax: 158156,
    phone: "+916480894105",
    email: "lucknow-public-school-vinamra-2224@example.com",
    website:
      "https://uniformapp.in/lucknow-public-school-vinamra-khand-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Lucknow_Public_School_Vinamra_Khand_Lucknow_image1_43.jpeg",
  },
  {
    name: "Fortune World School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "706835",
    address: "Sector-105",
    feesMin: 24968,
    feesMax: 89381,
    phone: "+918308230189",
    email: "fortune-world-school3564@example.com",
    website: "https://uniformapp.in/fortune-world-school-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Fortune_World_School_Noida_image1_159.jpeg",
  },
  {
    name: "Sapphire International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "709390",
    address: "Sector 70",
    feesMin: 10567,
    feesMax: 81173,
    phone: "+918580452824",
    email: "sapphire-international-school-505@example.com",
    website: "https://uniformapp.in/sapphire-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Sapphire_International_School_Noida_Noida_image1_193.jpeg",
  },
  {
    name: "The Paras World School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "906784",
    address: "Sector 50",
    feesMin: 43620,
    feesMax: 70489,
    phone: "+919981943697",
    email: "the-paras-world-school5965@example.com",
    website: "https://uniformapp.in/the-paras-world-school-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Paras_World_School_Gurgaon_image1_316.jpeg",
  },
  {
    name: "Pathways World School Aravali",
    board: "IB",
    medium: "English",
    type: "Public",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "632361",
    address: "Sohna Road",
    feesMin: 5286,
    feesMax: 50896,
    phone: "+918286351619",
    email: "pathways-world-school-aravali7352@example.com",
    website: "https://uniformapp.in/pathways-world-school-aravali-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Pathways_World_School_Aravali_Gurgaon_image1_1206.jpeg",
  },
  {
    name: "Lucknow Public School Vrindavan Yojna",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "129368",
    address: "Vrindavan Yojana",
    feesMin: 21159,
    feesMax: 91354,
    phone: "+919328038681",
    email: "lucknow-public-school-vrindava3237@example.com",
    website:
      "https://uniformapp.in/lucknow-public-school-vrindavan-yojna-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Lucknow_Public_School_Vrindavan_Yojna_Lucknow_image1_1225.jpeg",
  },
  {
    name: "Lucknow Public School Amrapali Yojna",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "601992",
    address: "Amrapali Yojna",
    feesMin: 18747,
    feesMax: 20298,
    phone: "+918036500358",
    email: "lucknow-public-school-amrapali3806@example.com",
    website:
      "https://uniformapp.in/lucknow-public-school-amrapali-yojna-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/LPS Amrapali Yojna Building Photo copy.jpg",
  },
  {
    name: "Lucknow Public School B-Block Rajajipuram",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "311784",
    address: "Block-B, Rajajipuram",
    feesMin: 6006,
    feesMax: 42927,
    phone: "+919436019845",
    email: "lucknow-public-school-b-block-5184@example.com",
    website:
      "https://uniformapp.in/lucknow-public-school-bblock-rajajipuram-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/b-block2.jpg",
  },
  {
    name: "Vidsan Charterhouse",
    board: "IB",
    medium: "English",
    type: "Public",
    city: "Faridabad",
    state: "Rajasthan",
    pinCode: "157773",
    address: "Sector 93",
    feesMin: 29587,
    feesMax: 135530,
    phone: "+917656500975",
    email: "vidsan-charterhouse3322@example.com",
    website: "https://uniformapp.in/vidsan-charterhouse-faridabad",
    image:
      "https://uniformapp.in/admin_area/school_images/Vidsan_Charterhouse_Faridabad_image1_1311.jpeg",
  },
  {
    name: "The Asian School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Dehradun",
    state: "Kerala",
    pinCode: "645689",
    address: "Vasant Vihar",
    feesMin: 16008,
    feesMax: 57353,
    phone: "+919259721598",
    email: "the-asian-school1375@example.com",
    website: "https://uniformapp.in/the-asian-school-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Asian_School_Dehradun_image1_2250.jpeg",
  },
  {
    name: "The Indian Cambridge School",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Dehradun",
    state: "Uttar Pradesh",
    pinCode: "923822",
    address: "Dalanwala",
    feesMin: 31742,
    feesMax: 180085,
    phone: "+918610554102",
    email: "the-indian-cambridge-school5760@example.com",
    website: "https://uniformapp.in/the-indian-cambridge-school-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/The Indian Cambridge School 12 Chander Road Dalanwala Dehradun3.jpg",
  },
  {
    name: "Ecole Globale International Girlsâ€™ School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Dehradun",
    state: "Kerala",
    pinCode: "114374",
    address: "Horawalla",
    feesMin: 30381,
    feesMax: 107067,
    phone: "+916845476218",
    email: "ecole-globale-international-gi5583@example.com",
    website:
      "https://uniformapp.in/ecole-globale-international-girls-school-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/Ecole_Globale_International_Girls_School_Dehradun_image1_2738.jpeg",
  },
  {
    name: "Lucknow Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Sitapur",
    state: "Delhi",
    pinCode: "382096",
    address: "Naveen Chowk",
    feesMin: 29718,
    feesMax: 157002,
    phone: "+918443000689",
    email: "lucknow-public-school1094@example.com",
    website: "https://uniformapp.in/lucknow-public-school-2131504-sitapur",
    image:
      "https://uniformapp.in/admin_area/school_images/lpcpssitapurlko01.jpg",
  },
  {
    name: "Manav Rachna International School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Ludhiana",
    state: "Karnataka",
    pinCode: "870663",
    address: "Dugri Road",
    feesMin: 17900,
    feesMax: 45539,
    phone: "+919762058057",
    email: "manav-rachna-international-sch7595@example.com",
    website:
      "https://uniformapp.in/manav-rachna-international-school-1631121-ludhiana",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "JES Public School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "635335",
    address: "Naagarabhaavi",
    feesMin: 45947,
    feesMax: 179644,
    phone: "+918369530492",
    email: "jes-public-school2824@example.com",
    website: "https://uniformapp.in/jes-public-school-830841-bengaluru",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Orchids The International School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "227283",
    address: "Orchids The International School, Bengaluru",
    feesMin: 8660,
    feesMax: 35906,
    phone: "+919930593852",
    email: "orchids-the-international-scho7113@example.com",
    website:
      "https://uniformapp.in/orchids-the-international-school-830782-bengaluru",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Swarnprastha Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Sonipat",
    state: "Kerala",
    pinCode: "242307",
    address: "Sector-19",
    feesMin: 35265,
    feesMax: 116087,
    phone: "+916730743430",
    email: "swarnprastha-public-school2582@example.com",
    website: "https://uniformapp.in/swarnprastha-public-school-530474-sonipat",
    image:
      "https://uniformapp.in/admin_area/school_images/Swarnprastha_Public_School_530474_Sonipat_image1_20566.jpeg",
  },

  {
    name: "The Doon Global School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Dehradun",
    state: "Karnataka",
    pinCode: "901401",
    address: "Jhajra",
    feesMin: 36912,
    feesMax: 70564,
    phone: "+919740462964",
    email: "the-doon-global-school146@example.com",
    website: "https://uniformapp.in/the-doon-global-school-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Doon_Global_School_Dehradun_image1_23125.jpeg",
  },
  {
    name: "Tula",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Dehradun",
    state: "Delhi",
    pinCode: "309586",
    address: "Selaqui",
    feesMin: 24626,
    feesMax: 45097,
    phone: "+916281992608",
    email: "tula7834@example.com",
    website:
      "https://uniformapp.in/tulas-international-school-dehradun-559123-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/Tulas_International_School_Dehradun_559123_Dehradun_image1_23202.jpeg",
  },
  {
    name: "SelaQui International School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Dehradun",
    state: "Maharashtra",
    pinCode: "870121",
    address: "Selaqui",
    feesMin: 19319,
    feesMax: 104308,
    phone: "+919337355652",
    email: "selaqui-international-school928@example.com",
    website:
      "https://uniformapp.in/selaqui-international-school-582402-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/SelaQui_International_School_582402_Dehradun_image1_23204.jpeg",
  },
  {
    name: "Doon Defence International School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Dehradun",
    state: "Kerala",
    pinCode: "569285",
    address: "Tapovan Nalapani",
    feesMin: 32973,
    feesMax: 163607,
    phone: "+916641093925",
    email: "doon-defence-international-sch6842@example.com",
    website: "https://uniformapp.in/doon-defence-international-school-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/Doon_Defence_International_School_Dehradun_image1_23228.jpeg",
  },
  {
    name: "Dehradun Hills Academy",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Dehradun",
    state: "Delhi",
    pinCode: "448611",
    address: "Doiwala-Doodhli Road",
    feesMin: 20584,
    feesMax: 69824,
    phone: "+918182976964",
    email: "dehradun-hills-academy3026@example.com",
    website: "https://uniformapp.in/dehradun-hills-academy-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/Dehradun_Hills_Academy_Dehradun_image1_23229.jpeg",
  },
  {
    name: "Seth Anandram Jaipuria, Alambagh Campus",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "174243",
    address: "Alambagh",
    feesMin: 48030,
    feesMax: 87413,
    phone: "+919916652350",
    email: "seth-anandram-jaipuria-alambag6545@example.com",
    website:
      "https://uniformapp.in/seth-anandram-jaipuria-alambagh-campus-3404834-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Seth_Anandram_Jaipuria_Alambagh_Campus_3404834_Lucknow_image1_23230.jpeg",
  },
  {
    name: "The TonsBridge School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Dehradun",
    state: "Tamil Nadu",
    pinCode: "741233",
    address: "Pondha",
    feesMin: 38788,
    feesMax: 87577,
    phone: "+919321741712",
    email: "the-tonsbridge-school1213@example.com",
    website: "https://uniformapp.in/the-tonsbridge-school-355683-dehradun",
    image:
      "https://uniformapp.in/admin_area/school_images/The_TonsBridge_School_355683_Dehradun_image1_25656.jpeg",
  },
  {
    name: "Good Word Public School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Chennai",
    state: "Tamil Nadu",
    pinCode: "240887",
    address: "Redhills",
    feesMin: 15246,
    feesMax: 133465,
    phone: "+917120877125",
    email: "good-word-public-school9205@example.com",
    website: "https://uniformapp.in/good-word-public-school-209210-chennai",
    image:
      "https://uniformapp.in/admin_area/school_images/Good_Word_Public_School_209210_Chennai_image1_25847.jpeg",
  },
  {
    name: "CP Goenka School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Pune",
    state: "Rajasthan",
    pinCode: "673010",
    address: "Ubale Nagar",
    feesMin: 8025,
    feesMax: 81991,
    phone: "+917489400005",
    email: "cp-goenka-school280@example.com",
    website: "https://uniformapp.in/cp-goenka-school-740211-pune",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Manav Rachna International School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Mohali",
    state: "Haryana",
    pinCode: "535769",
    address: "Sahibzada Ajit Singh Nagar",
    feesMin: 11994,
    feesMax: 126395,
    phone: "+918308262092",
    email: "manav-rachna-international-sch643@example.com",
    website:
      "https://uniformapp.in/manav-rachna-international-school-183450-mohali",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Vidyashilp School",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "755073",
    address: "Chagalatti",
    feesMin: 45201,
    feesMax: 127232,
    phone: "+918523323444",
    email: "vidyashilp-school8664@example.com",
    website: "https://uniformapp.in/vidyashilp-school-145334-bengaluru",
    image:
      "https://uniformapp.in/admin_area/school_images/Vidyashilp_School_145334_Bengaluru_image1_25854.jpeg",
  },
  {
    name: "Pallavi Model School Bowenpally",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "523629",
    address: "Secunderabad",
    feesMin: 17925,
    feesMax: 108637,
    phone: "+916312806501",
    email: "pallavi-model-school-bowenpall2770@example.com",
    website:
      "https://uniformapp.in/pallavi-model-school-bowenpally-853760-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Pallavi Model School Boduppal",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "603442",
    address: "Boduppal",
    feesMin: 49973,
    feesMax: 128094,
    phone: "+916158229562",
    email: "pallavi-model-school-boduppal8939@example.com",
    website:
      "https://uniformapp.in/pallavi-model-school-boduppal-921496-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Pallavi Aware International School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "472942",
    address: "Saroornagar",
    feesMin: 47971,
    feesMax: 155269,
    phone: "+918435564922",
    email: "pallavi-aware-international-sc4134@example.com",
    website:
      "https://uniformapp.in/pallavi-aware-international-school-413496-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Pallavi Model School Alwal",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "790865",
    address: "Secunderabad",
    feesMin: 5832,
    feesMax: 22279,
    phone: "+916464221007",
    email: "pallavi-model-school-alwal8782@example.com",
    website:
      "https://uniformapp.in/pallavi-model-school-alwal-814106-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Pallavi International School Gandipet",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "473263",
    address: "Moinabad Mandal",
    feesMin: 17779,
    feesMax: 107583,
    phone: "+918148164438",
    email: "pallavi-international-school-g248@example.com",
    website:
      "https://uniformapp.in/pallavi-international-school-gandipet-214044-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Pallavi International School Keesara",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "126822",
    address: "Keesara Mandal",
    feesMin: 6058,
    feesMax: 144657,
    phone: "+916552877323",
    email: "pallavi-international-school-k74@example.com",
    website:
      "https://uniformapp.in/pallavi-international-school-keesara-845151-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Kairos International School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "966615",
    address: "Gachibowli",
    feesMin: 21205,
    feesMax: 59844,
    phone: "+919049278676",
    email: "kairos-international-school6288@example.com",
    website:
      "https://uniformapp.in/kairos-international-school-583544-hyderabad",
    image:
      "https://uniformapp.in/admin_area/school_images/Kairos_International_School_583544_Hyderabad_image1_25862.jpeg",
  },
  {
    name: "Orchids The International School Kapra",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "759521",
    address: "Secunderabad",
    feesMin: 11927,
    feesMax: 16775,
    phone: "+916008126321",
    email: "orchids-the-international-scho7872@example.com",
    website:
      "https://uniformapp.in/orchids-the-international-school-kapra-492834-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Smt. Kamalabai Educational Institution",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "412061",
    address: "Off Queens Road Cross",
    feesMin: 40921,
    feesMax: 129977,
    phone: "+919656027173",
    email: "smt-kamalabai-educational-inst7675@example.com",
    website:
      "https://uniformapp.in/smt-kamalabai-educational-institution-136108-bengaluru",
    image:
      "https://uniformapp.in/admin_area/school_images/Smt_Kamalabai_Educational_Institution_136108_Bengaluru_image1_25865.jpeg",
  },

  {
    name: "Orchids The International School Ambegaon",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Pune",
    state: "Maharashtra",
    pinCode: "792033",
    address: "Ambegaon",
    feesMin: 8071,
    feesMax: 56797,
    phone: "+918856444339",
    email: "orchids-the-international-scho886@example.com",
    website:
      "https://uniformapp.in/orchids-the-international-school-ambegaon-208139-pune",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "JP International School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Greater",
    state: "Kerala",
    pinCode: "707771",
    address: "Omega 1",
    feesMin: 24071,
    feesMax: 53807,
    phone: "+918005130703",
    email: "jp-international-school972@example.com",
    website:
      "https://uniformapp.in/jp-international-school-969286-greater+noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Shree Swaminarayan Gurukul International School Secunderabad",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "219598",
    address: "Secunderabad",
    feesMin: 16050,
    feesMax: 27989,
    phone: "+918543938902",
    email: "shree-swaminarayan-gurukul-int1926@example.com",
    website:
      "https://uniformapp.in/shree-swaminarayan-gurukul-international-school-secunderabad-117266-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Akshara International School, LB Nagar",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "562749",
    address: "Bairamalguda",
    feesMin: 17275,
    feesMax: 92368,
    phone: "+918759034890",
    email: "akshara-international-school-l6521@example.com",
    website:
      "https://uniformapp.in/akshara-international-school-lb-nagar-385107-hyderabad",
    image:
      "https://uniformapp.in/admin_area/school_images/Akshara_International_School_LB_Nagar_385107_Hyderabad_image1_25874.jpeg",
  },
  {
    name: "D Y Patil International School",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Pune",
    state: "Karnataka",
    pinCode: "778390",
    address: "Lohegaon",
    feesMin: 37017,
    feesMax: 163926,
    phone: "+916056571211",
    email: "d-y-patil-international-school4728@example.com",
    website: "https://uniformapp.in/d-y-patil-international-school-970736-pune",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Solitaire Global School, Attapur",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "732018",
    address: "Upparpally",
    feesMin: 28264,
    feesMax: 29728,
    phone: "+916916042682",
    email: "solitaire-global-school-attapu7560@example.com",
    website:
      "https://uniformapp.in/solitaire-global-school-attapur-405079-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Solitaire Global School, Katedan",
    board: "State Board",
    medium: "Hindi",
    type: "Aided",
    city: "Hyderabad",
    state: "Telangana",
    pinCode: "563360",
    address: "Katedan",
    feesMin: 41695,
    feesMax: 104849,
    phone: "+916191386085",
    email: "solitaire-global-school-kateda1282@example.com",
    website:
      "https://uniformapp.in/solitaire-global-school-katedan-956735-hyderabad",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Excellia School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "445387",
    address: "Raebareli road",
    feesMin: 21306,
    feesMax: 125572,
    phone: "+919457510562",
    email: "excellia-school8299@example.com",
    website: "https://uniformapp.in/excellia-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/EXS.jpg",
  },
  {
    name: "The Hamilton Academy",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "548189",
    address: "Alambagh",
    feesMin: 22438,
    feesMax: 110754,
    phone: "+919198834526",
    email: "the-hamilton-academy4626@example.com",
    website: "https://uniformapp.in/the-hamilton-academy-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/hamiltonacad.jpeg",
  },
  {
    name: "Lucknow International Public School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "588642",
    address: "Sitapur Road",
    feesMin: 20429,
    feesMax: 93825,
    phone: "+918356858606",
    email: "lucknow-international-public-s651@example.com",
    website:
      "https://uniformapp.in/lucknow-international-public-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/lips.jpg",
  },
  {
    name: "Indus Valley Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "664631",
    address: "IIM Road",
    feesMin: 22327,
    feesMax: 86090,
    phone: "+919634501877",
    email: "indus-valley-public-school4521@example.com",
    website: "https://uniformapp.in/indus-valley-public-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/IVPS.png",
  },
  {
    name: "Loyola International School Gomti Nagar",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "385033",
    address: "Gomti Nagar",
    feesMin: 48979,
    feesMax: 163974,
    phone: "+916960822590",
    email: "loyola-international-school-go6523@example.com",
    website:
      "https://uniformapp.in/loyola-international-school-gomti-nagar-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Loyola-Public-School-Gomti-Nagar.png",
  },
  {
    name: "RK Senior Secondary School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "141475",
    address: "Aliganj",
    feesMin: 48981,
    feesMax: 127063,
    phone: "+919435489485",
    email: "rk-senior-secondary-school5552@example.com",
    website: "https://uniformapp.in/rk-senior-secondary-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/rksss_pic.jpg",
  },
  {
    name: "Nannhe Munhe",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Maharashtra",
    pinCode: "547874",
    address: "Aliganj",
    feesMin: 26440,
    feesMax: 169557,
    phone: "+917500423397",
    email: "nannhe-munhe5928@example.com",
    website: "https://uniformapp.in/nannhe-munhe-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/nanhemunhe.jpg",
  },
  {
    name: "GD Goenka Public School Shaheed Path",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Maharashtra",
    pinCode: "368461",
    address: "Gomti Nagar",
    feesMin: 23805,
    feesMax: 134820,
    phone: "+918220199275",
    email: "gd-goenka-public-school-shahee742@example.com",
    website:
      "https://uniformapp.in/gd-goenka-public-school-shaheed-path-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/GD_Goenka_Public_School_Shaheed_Path_Lucknow_image1_6.jpeg",
  },
  {
    name: "Scholars",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "322318",
    address: "Gomti Nagar",
    feesMin: 25267,
    feesMax: 74648,
    phone: "+918420234073",
    email: "scholars6159@example.com",
    website: "https://uniformapp.in/scholars-home-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Scholars_Home_Lucknow_image1_8.jpeg",
  },
  {
    name: "The Avadh School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "435373",
    address: "Gomti Nagar",
    feesMin: 8876,
    feesMax: 107959,
    phone: "+916437434027",
    email: "the-avadh-school6885@example.com",
    website: "https://uniformapp.in/the-avadh-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Avadh_School_Lucknow_image1_9.jpeg",
  },
  {
    name: "Loyola International School Mahanagar",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "581659",
    address: "Mahanagar",
    feesMin: 23445,
    feesMax: 97481,
    phone: "+916642928713",
    email: "loyola-international-school-ma4984@example.com",
    website:
      "https://uniformapp.in/loyola-international-school-mahanagar-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/loyala mahanagar.jpg",
  },
  {
    name: "CMS Aliganj I",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "197681",
    address: "Aliganj",
    feesMin: 19876,
    feesMax: 106215,
    phone: "+919646582691",
    email: "cms-aliganj-i9891@example.com",
    website: "https://uniformapp.in/cms-aliganj-i-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Aliganj_I_Lucknow_image1_12.jpeg",
  },
  {
    name: "Study Hall School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "739170",
    address: "Gomti Nagar",
    feesMin: 36438,
    feesMax: 141436,
    phone: "+919356638831",
    email: "study-hall-school3399@example.com",
    website: "https://uniformapp.in/study-hall-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Study_Hall_School_Lucknow_image1_14.jpeg",
  },

  {
    name: "Modern Academy",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "310393",
    address: "Gomti Nagar",
    feesMin: 36708,
    feesMax: 100291,
    phone: "+917691147662",
    email: "modern-academy7256@example.com",
    website: "https://uniformapp.in/modern-academy-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/building.gif",
  },
  {
    name: "Cathedral School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "451556",
    address: "Hazratganj",
    feesMin: 49813,
    feesMax: 137113,
    phone: "+917968400998",
    email: "cathedral-school6579@example.com",
    website: "https://uniformapp.in/cathedral-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Cathedral-School.jpg",
  },
  {
    name: "La Martiniere Girls College",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "547024",
    address: "Hazratganj",
    feesMin: 49528,
    feesMax: 90225,
    phone: "+919259944635",
    email: "la-martiniere-girls-college734@example.com",
    website: "https://uniformapp.in/la-martiniere-girls-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/La_Martiniere_Girls_College_Lucknow_image1_17.jpeg",
  },
  {
    name: "Seth MR Jaipuria School",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "533095",
    address: "Gomti Nagar",
    feesMin: 36246,
    feesMax: 47208,
    phone: "+916843419829",
    email: "seth-mr-jaipuria-school5985@example.com",
    website: "https://uniformapp.in/seth-mr-jaipuria-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/seth mr jaipuria.jpg",
  },
  {
    name: "St Francis College",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Telangana",
    pinCode: "612576",
    address: "Hazratganj",
    feesMin: 28126,
    feesMax: 67054,
    phone: "+918304997595",
    email: "st-francis-college2168@example.com",
    website: "https://uniformapp.in/st-francis-college-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/st francis.jpg",
  },
  {
    name: "Spring Dale School Gomti Nagar",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "518990",
    address: "Gomti Nagar",
    feesMin: 16614,
    feesMax: 140020,
    phone: "+917068629183",
    email: "spring-dale-school-gomti-nagar3640@example.com",
    website: "https://uniformapp.in/spring-dale-school-gomti-nagar-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Spring_Dale_School_Gomti_Nagar_Lucknow_image1_21.jpeg",
  },
  {
    name: "Spring Dale School Kanpur Road",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "333134",
    address: "Spring Dale School Kanpur Road, Lucknow",
    feesMin: 23743,
    feesMax: 112346,
    phone: "+919938109398",
    email: "spring-dale-school-kanpur-road4694@example.com",
    website: "https://uniformapp.in/spring-dale-school-kanpur-road-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/springdale kprd.jpg",
  },
  {
    name: "Spring Dale School Indira Nagar",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "296965",
    address: "Indira Nagar",
    feesMin: 30483,
    feesMax: 146492,
    phone: "+919963221864",
    email: "spring-dale-school-indira-naga3562@example.com",
    website: "https://uniformapp.in/spring-dale-school-indira-nagar-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/springdalemn.jpg",
  },
  {
    name: "Loreto Convent College",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "626737",
    address: "Gulistan Colony",
    feesMin: 38733,
    feesMax: 58312,
    phone: "+919351043754",
    email: "loreto-convent-college8247@example.com",
    website: "https://uniformapp.in/loreto-convent-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Loreto_Convent_College_Lucknow_image1_24.jpeg",
  },
  {
    name: "St. Agnes Loreto School",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "209178",
    address: "Station Road",
    feesMin: 25672,
    feesMax: 173886,
    phone: "+918361806449",
    email: "st-agnes-loreto-school2517@example.com",
    website: "https://uniformapp.in/st-agnes-loreto-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/St_Agnes_Loreto_School_Lucknow_image1_25.jpeg",
  },
  {
    name: "Emma Thompson School",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "360082",
    address: "Lalbagh",
    feesMin: 38867,
    feesMax: 103964,
    phone: "+917778836189",
    email: "emma-thompson-school6699@example.com",
    website: "https://uniformapp.in/emma-thompson-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/banner1.jpg",
  },
  {
    name: "Army Public School Nehru Road",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "271533",
    address: "Cantonment",
    feesMin: 6419,
    feesMax: 55997,
    phone: "+918515049449",
    email: "army-public-school-nehru-road6046@example.com",
    website: "https://uniformapp.in/army-public-school-nehru-road-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/army-public-school-lucknow-lucknow-schools-4dasas7.jpg",
  },
  {
    name: "Army Public School LBS Marg",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "547850",
    address: "Cantonment",
    feesMin: 37062,
    feesMax: 159978,
    phone: "+916060384938",
    email: "army-public-school-lbs-marg3466@example.com",
    website: "https://uniformapp.in/army-public-school-lbs-marg-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/army-public-school-lucknow-LBS MARG.jpg",
  },
  {
    name: "CMS Gomtinagar I",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "816231",
    address: "Gomti Nagar",
    feesMin: 44861,
    feesMax: 83330,
    phone: "+917326692563",
    email: "cms-gomtinagar-i9499@example.com",
    website: "https://uniformapp.in/cms-gomtinagar-i-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Gomtinagar_I_Lucknow_image1_29.jpeg",
  },
  {
    name: "St. Teresa Day School Model House",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "855265",
    address: "Lalbagh",
    feesMin: 15383,
    feesMax: 71686,
    phone: "+919423246262",
    email: "st-teresa-day-school-model-hou9645@example.com",
    website: "https://uniformapp.in/st-teresa-day-school-model-house-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/stteresamh.jpg",
  },
  {
    name: "Colvin Taluqdars College",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "897893",
    address: "Kaiserbagh",
    feesMin: 32080,
    feesMax: 68082,
    phone: "+916624988797",
    email: "colvin-taluqdars-college7573@example.com",
    website: "https://uniformapp.in/colvin-taluqdars-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Colvin Taluqdars College.JPG",
  },
  {
    name: "St. John Bosco College",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "422244",
    address: "Gomti Nagar",
    feesMin: 39625,
    feesMax: 142671,
    phone: "+918601206209",
    email: "st-john-bosco-college250@example.com",
    website: "https://uniformapp.in/st-john-bosco-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/St. John Bosco College.jpg",
  },
  {
    name: "Little Audrey Play School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "693556",
    address: "Sitapur Road",
    feesMin: 28049,
    feesMax: 47800,
    phone: "+918241026144",
    email: "little-audrey-play-school9187@example.com",
    website: "https://uniformapp.in/little-audrey-play-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/littleaudreya.jpg",
  },
  {
    name: "Indus Valley Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "689530",
    address: "Institutional Area",
    feesMin: 44599,
    feesMax: 137292,
    phone: "+917252759540",
    email: "indus-valley-public-school-noi8534@example.com",
    website: "https://uniformapp.in/indus-valley-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Indus_Valley_Public_School_Noida_Noida_image1_34.jpeg",
  },
  {
    name: "Braeburn Preschool",
    board: "State Board",
    medium: "Hindi",
    type: "Government",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "589636",
    address: "Vrindavan Colony",
    feesMin: 17760,
    feesMax: 44903,
    phone: "+918004087396",
    email: "braeburn-preschool1577@example.com",
    website: "https://uniformapp.in/braeburn-preschool-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/braeburn.png",
  },

  {
    name: "Riverside Academy",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Maharashtra",
    pinCode: "134221",
    address: "Gomti Nagar",
    feesMin: 45737,
    feesMax: 142882,
    phone: "+916857863643",
    email: "riverside-academy454@example.com",
    website: "https://uniformapp.in/riverside-academy-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/riverside-academy-inter-college-gomti-nagar-lucknow-schools-12ok7sv.jpg",
  },
  {
    name: "ARVIND ACADEMY",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "933262",
    address: "Gomti Nagar",
    feesMin: 23853,
    feesMax: 133792,
    phone: "+917179115584",
    email: "arvind-academy2856@example.com",
    website: "https://uniformapp.in/arvind-academy-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/1018.jpg",
  },
  {
    name: "Career Convent College",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "959984",
    address: "Vikas Nagar",
    feesMin: 44964,
    feesMax: 57777,
    phone: "+918753812922",
    email: "career-convent-college2@example.com",
    website: "https://uniformapp.in/career-convent-college-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/ccc.jpg",
  },
  {
    name: "St. Xaviers Convent School",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "599880",
    address: "Gomti Nagar",
    feesMin: 32954,
    feesMax: 172073,
    phone: "+916091971620",
    email: "st-xaviers-convent-school1637@example.com",
    website: "https://uniformapp.in/st-xaviers-convent-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/st-xavier-convent-school-gomti-nagar-lucknow-english-medium-schools-452hktu.jpg",
  },
  {
    name: "CMS Rajajipuram",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "678621",
    address: "Rajajipuram",
    feesMin: 29331,
    feesMax: 129543,
    phone: "+916689565204",
    email: "cms-rajajipuram292@example.com",
    website: "https://uniformapp.in/cms-rajajipuram-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Rajajipuram_Lucknow_image1_41.jpeg",
  },
  {
    name: "CMS Rajendra Nagar",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "660886",
    address: "Rajendra Nagar",
    feesMin: 42947,
    feesMax: 140277,
    phone: "+918182708252",
    email: "cms-rajendra-nagar7641@example.com",
    website: "https://uniformapp.in/cms-rajendra-nagar-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Rajendra_Nagar_Lucknow_image1_42.jpeg",
  },
  {
    name: "Dr. Virendra Swarup Public School",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "202019",
    address: "Mahanagar",
    feesMin: 8493,
    feesMax: 104949,
    phone: "+918452360233",
    email: "dr-virendra-swarup-public-scho738@example.com",
    website: "https://uniformapp.in/dr-virendra-swarup-public-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-19 at 9.50.47 PM.jpeg",
  },
  {
    name: "Tender Little Heart Kursi Road",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "202019",
    address: "Kursi Road",
    feesMin: 14818,
    feesMax: 132105,
    phone: "+917600413602",
    email: "tender-little-heart-kursi-road2073@example.com",
    website: "https://uniformapp.in/tender-little-heart-kursi-road-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-19 at 11.39.07 PM(3).jpeg",
  },
  {
    name: "Tender Hearts Jankipuram",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "202019",
    address: "Jankipuram",
    feesMin: 11598,
    feesMax: 109910,
    phone: "+917078359499",
    email: "tender-hearts-jankipuram1170@example.com",
    website: "https://uniformapp.in/tender-hearts-jankipuram-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-19 at 11.39.07 PM(2).jpeg",
  },
  {
    name: "Navayuga Radiance Senior Secondary School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "514294",
    address: "Rajendra Nagar",
    feesMin: 12527,
    feesMax: 73006,
    phone: "+917690403522",
    email: "navayuga-radiance-senior-secon1324@example.com",
    website:
      "https://uniformapp.in/navayuga-radiance-senior-secondary-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/schoolpic2.jpg",
  },
  {
    name: "APS Academy",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "333728",
    address: "Telibagh",
    feesMin: 46226,
    feesMax: 129829,
    phone: "+916864123493",
    email: "aps-academy4133@example.com",
    website: "https://uniformapp.in/aps-academy-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/aps-academy-telibagh-lucknow-schools-fx9ft.jpg",
  },
  {
    name: "HAL School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "400357",
    address: "Faizabad Road",
    feesMin: 19018,
    feesMax: 25922,
    phone: "+917368739638",
    email: "hal-school693@example.com",
    website: "https://uniformapp.in/hal-school-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/4.jpg",
  },
  {
    name: "St. Fidelis College",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "727125",
    address: "Aliganj",
    feesMin: 13547,
    feesMax: 142121,
    phone: "+918187249363",
    email: "st-fidelis-college2666@example.com",
    website: "https://uniformapp.in/st-fidelis-college-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/slide4.jpg",
  },
  {
    name: "Modern School",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Rajasthan",
    pinCode: "359775",
    address: "Aliganj",
    feesMin: 44459,
    feesMax: 66102,
    phone: "+919510343141",
    email: "modern-school4115@example.com",
    website: "https://uniformapp.in/modern-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/Screen-Shot-2018-04-03-at-11.06.30-AM-461x458.jpg",
  },
  {
    name: "City International School Balaganj",
    board: "ICSE",
    medium: "English",
    type: "Aided",
    city: "Lucknow",
    state: "Telangana",
    pinCode: "554607",
    address: "Balaganj",
    feesMin: 31240,
    feesMax: 94596,
    phone: "+918400523379",
    email: "city-international-school-bala5229@example.com",
    website: "https://uniformapp.in/city-international-school-balaganj-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/city-international-school-balaganj-lucknow-schools-dflnv.jpg",
  },
  {
    name: "Daffodils Play School",
    board: "ICSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Karnataka",
    pinCode: "202019",
    address: "Jankipuram",
    feesMin: 45618,
    feesMax: 109464,
    phone: "+919293812450",
    email: "daffodils-play-school7296@example.com",
    website: "https://uniformapp.in/daffodils-play-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-23 at 6.25.02 PM.jpeg",
  },
  {
    name: "St. Francis School",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "202019",
    address: "Gomti Nagar",
    feesMin: 45995,
    feesMax: 99006,
    phone: "+918487198917",
    email: "st-francis-school1015@example.com",
    website: "https://uniformapp.in/st-francis-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-24 at 2.37.56 PM(1).jpeg",
  },
  {
    name: "CMS Gomti Nagar II",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Telangana",
    pinCode: "174154",
    address: "Gomti Nagar",
    feesMin: 34187,
    feesMax: 182536,
    phone: "+917191590352",
    email: "cms-gomti-nagar-ii941@example.com",
    website: "https://uniformapp.in/cms-gomti-nagar-ii-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Gomti_Nagar_II_Lucknow_image1_127.jpeg",
  },
  {
    name: "CMS Aliganj II",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "699215",
    address: "Aliganj",
    feesMin: 43443,
    feesMax: 152676,
    phone: "+918143989514",
    email: "cms-aliganj-ii6877@example.com",
    website: "https://uniformapp.in/cms-aliganj-ii-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Aliganj_II_Lucknow_image1_128.jpeg",
  },
  {
    name: "Central Academy Aashiyana",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "761244",
    address: "Ashiyana",
    feesMin: 30628,
    feesMax: 109721,
    phone: "+916526694398",
    email: "central-academy-aashiyana773@example.com",
    website: "https://uniformapp.in/central-academy-aashiyana-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/ashiana.jpg",
  },

  {
    name: "Gurgaon School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Lucknow",
    state: "Tamil Nadu",
    pinCode: "827355",
    address: "Shaheed Path Road",
    feesMin: 41572,
    feesMax: 179245,
    phone: "+917063321826",
    email: "gurgaon-school3124@example.com",
    website: "https://uniformapp.in/gurgaon-school--lucknow",
    image: "https://uniformapp.in/admin_area/school_images/images.jpg",
  },
  {
    name: "St. Paul College",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Maharashtra",
    pinCode: "202019",
    address: "Lucknow Cantt",
    feesMin: 13532,
    feesMax: 124883,
    phone: "+917293138444",
    email: "st-paul-college4570@example.com",
    website: "https://uniformapp.in/st-paul-college-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/WhatsApp Image 2019-03-24 at 2.01.41 PM.jpeg",
  },
  {
    name: "The Millennium School Sitapur Road",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Lucknow",
    state: "Telangana",
    pinCode: "557704",
    address: "Sitapur Road",
    feesMin: 11531,
    feesMax: 96858,
    phone: "+918425386039",
    email: "the-millennium-school-sitapur-5599@example.com",
    website: "https://uniformapp.in/the-millennium-school-sitapur-road-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/millennium sitapur road.jpg",
  },
  {
    name: "Isabella Thoburn Intermediate College",
    board: "State Board",
    medium: "English & Hindi",
    type: "Government",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "778906",
    address: "Faizabad Road",
    feesMin: 17811,
    feesMax: 66167,
    phone: "+916418392187",
    email: "isabella-thoburn-intermediate-6077@example.com",
    website:
      "https://uniformapp.in/isabella-thoburn-intermediate-college-lucknow",
    image: "https://uniformapp.in/admin_area/school_images/itcollege.jpg",
  },
  {
    name: "Shri Ramswaroop Memorial Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Haryana",
    pinCode: "820888",
    address: "Faizabad Road",
    feesMin: 11314,
    feesMax: 117912,
    phone: "+918635344144",
    email: "shri-ramswaroop-memorial-publi4160@example.com",
    website:
      "https://uniformapp.in/shri-ramswaroop-memorial-public-school-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/SRMPS_-_Shri_Ramswaroop_Memorial_Public_School.jpg",
  },
  {
    name: "CMS Indira Nagar",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Delhi",
    pinCode: "841173",
    address: "Indira Nagar",
    feesMin: 38638,
    feesMax: 104335,
    phone: "+917765228093",
    email: "cms-indira-nagar2726@example.com",
    website: "https://uniformapp.in/cms-indira-nagar-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Indira_Nagar_Lucknow_image1_135.jpeg",
  },
  {
    name: "CMS Kanpur Road",
    board: "ICSE",
    medium: "English",
    type: "Public",
    city: "Lucknow",
    state: "Kerala",
    pinCode: "816687",
    address: "Kanpur Road",
    feesMin: 36577,
    feesMax: 58637,
    phone: "+918534674267",
    email: "cms-kanpur-road4270@example.com",
    website: "https://uniformapp.in/cms-kanpur-road-lucknow",
    image:
      "https://uniformapp.in/admin_area/school_images/CMS_Kanpur_Road_Lucknow_image1_136.jpeg",
  },
  {
    name: "Pathways School Noida",
    board: "State Board",
    medium: "Hindi",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "306744",
    address: "Sector 100",
    feesMin: 9262,
    feesMax: 144664,
    phone: "+918352829650",
    email: "pathways-school-noida8373@example.com",
    website: "https://uniformapp.in/pathways-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Pathways_School_Noida_Noida_image1_138.jpeg",
  },
  {
    name: "The Shriram Millennium School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "355662",
    address: "Sector 135",
    feesMin: 14179,
    feesMax: 66406,
    phone: "+916944654273",
    email: "the-shriram-millennium-school-2430@example.com",
    website: "https://uniformapp.in/the-shriram-millennium-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Shriram_Millennium_School_Noida_Noida_image1_139.jpeg",
  },
  {
    name: "Apeejay School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "318621",
    address: "Film City",
    feesMin: 19932,
    feesMax: 169050,
    phone: "+918872933919",
    email: "apeejay-school-noida1597@example.com",
    website: "https://uniformapp.in/apeejay-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Apeejay_School_Noida_Noida_image1_141.jpeg",
  },
  {
    name: "Somerville School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "878799",
    address: "Gautam Buddh Nagar",
    feesMin: 33578,
    feesMax: 78469,
    phone: "+917926821505",
    email: "somerville-school-noida8930@example.com",
    website: "https://uniformapp.in/somerville-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Somerville_School_Noida_Noida_image1_142.jpeg",
  },
  {
    name: "Lotus Valley International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "243239",
    address: "Expressway",
    feesMin: 32159,
    feesMax: 100549,
    phone: "+917187773058",
    email: "lotus-valley-international-sch9195@example.com",
    website:
      "https://uniformapp.in/lotus-valley-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Lotus_Valley_International_School_Noida_Noida_image1_143.jpeg",
  },
  {
    name: "Delhi Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "117488",
    address: "Sector 30",
    feesMin: 40194,
    feesMax: 103973,
    phone: "+916335789066",
    email: "delhi-public-school-noida3040@example.com",
    website: "https://uniformapp.in/delhi-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Delhi_Public_School_Noida_Noida_image1_144.jpeg",
  },
  {
    name: "Amity International Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "914308",
    address: "Sector-44",
    feesMin: 15257,
    feesMax: 95866,
    phone: "+918876681347",
    email: "amity-international-noida7531@example.com",
    website: "https://uniformapp.in/amity-international-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_International_Noida_Noida_image1_145.jpeg",
  },
  {
    name: "The Khaitan School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "900771",
    address: "Sector 40",
    feesMin: 38263,
    feesMax: 54078,
    phone: "+917703535454",
    email: "the-khaitan-school-noida2835@example.com",
    website: "https://uniformapp.in/the-khaitan-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Khaitan_School_Noida_Noida_image1_146.jpeg",
  },
  {
    name: "Adarsh Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "137907",
    address: "Gautam Budha Nagar",
    feesMin: 43115,
    feesMax: 191142,
    phone: "+919858902369",
    email: "adarsh-public-school-noida3757@example.com",
    website: "https://uniformapp.in/adarsh-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Adarsh_Public_School_Noida_Noida_image1_147.jpeg",
  },
  {
    name: "Amar Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "851210",
    address: "Sector 37",
    feesMin: 27574,
    feesMax: 107952,
    phone: "+917756276831",
    email: "amar-public-school-noida837@example.com",
    website: "https://uniformapp.in/amar-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Amar_Public_School_Noida_Noida_image1_148.jpeg",
  },
  {
    name: "Amity Global School Noida",
    board: "ICSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "912682",
    address: "Sector 44",
    feesMin: 32616,
    feesMax: 43314,
    phone: "+917851694574",
    email: "amity-global-school-noida8249@example.com",
    website: "https://uniformapp.in/amity-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_Global_School_Noida_Noida_image1_149.jpeg",
  },
  {
    name: "Amity International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "169216",
    address: "Sector-44",
    feesMin: 49041,
    feesMax: 102760,
    phone: "+916144195394",
    email: "amity-international-school-noi621@example.com",
    website: "https://uniformapp.in/amity-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_International_School_Noida_Noida_image1_150.jpeg",
  },
  {
    name: "Army Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "407425",
    address: "Arun Vihar",
    feesMin: 35455,
    feesMax: 64528,
    phone: "+916960567772",
    email: "army-public-school-noida2317@example.com",
    website: "https://uniformapp.in/army-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Army_Public_School_Noida_Noida_image1_151.jpeg",
  },
  {
    name: "Assisi Convent School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "634247",
    address: "Sector 33",
    feesMin: 31008,
    feesMax: 158181,
    phone: "+918747783610",
    email: "assisi-convent-school-noida4135@example.com",
    website: "https://uniformapp.in/assisi-convent-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Assisi_Convent_School_Noida_Noida_image1_152.jpeg",
  },
  {
    name: "Billabong High International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "830241",
    address: "Sector 34",
    feesMin: 48056,
    feesMax: 143933,
    phone: "+917776822638",
    email: "billabong-high-international-s9950@example.com",
    website:
      "https://uniformapp.in/billabong-high-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Billabong_High_International_School_Noida_Noida_image1_153.jpeg",
  },
  {
    name: "Cambridge School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "886232",
    address: "Gautam Budh Nagar",
    feesMin: 36870,
    feesMax: 95588,
    phone: "+917429574275",
    email: "cambridge-school-noida5381@example.com",
    website: "https://uniformapp.in/cambridge-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Cambridge_School_Noida_Noida_image1_154.jpeg",
  },
  {
    name: "City Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "647134",
    address: "Sector 61",
    feesMin: 43502,
    feesMax: 155369,
    phone: "+917568316461",
    email: "city-public-school-noida743@example.com",
    website: "https://uniformapp.in/city-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/City_Public_School_Noida_Noida_image1_155.jpeg",
  },
  {
    name: "COSMOS PUBLIC School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "New",
    state: "Karnataka",
    pinCode: "435066",
    address: "COSMOS PUBLIC School Noida, New",
    feesMin: 45861,
    feesMax: 119017,
    phone: "+919842264366",
    email: "cosmos-public-school-noida8553@example.com",
    website: "https://uniformapp.in/cosmos-public-school-noida-new+delhi",
    image:
      "https://uniformapp.in/admin_area/school_images/COSMOS PUBLIC SCHOOL Molarbandekta Viharbadarpur Delhi18.jpg",
  },
  {
    name: "Delhi Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "738561",
    address: "Gautam Buddh Nagar",
    feesMin: 34958,
    feesMax: 48840,
    phone: "+916604443361",
    email: "delhi-public-school-noida1440@example.com",
    website: "https://uniformapp.in/delhi-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Delhi_Public_School_Noida_Noida_image1_157.jpeg",
  },
  {
    name: "Delhi Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "576501",
    address: "Sector-30",
    feesMin: 31290,
    feesMax: 141059,
    phone: "+918476658675",
    email: "delhi-public-school-noida3575@example.com",
    website: "https://uniformapp.in/delhi-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Delhi_Public_School_Noida_Noida_image1_158.jpeg",
  },
  {
    name: "GANGA DEVI PUBLIC School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "New",
    state: "Rajasthan",
    pinCode: "443962",
    address: "GANGA DEVI PUBLIC School Noida, New",
    feesMin: 27106,
    feesMax: 153728,
    phone: "+917064339604",
    email: "ganga-devi-public-school-noida1464@example.com",
    website: "https://uniformapp.in/ganga-devi-public-school-noida-new+delhi",
    image:
      "https://uniformapp.in/admin_area/school_images/GANGA DEVI PUBLIC SCHOOL E 6 Om Nagar Meeta Pur Badarpur N.d.44 Delhi1.jpg",
  },
  {
    name: "Genesis Global School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "195814",
    address: "Sector - 132",
    feesMin: 28737,
    feesMax: 169675,
    phone: "+917074415779",
    email: "genesis-global-school-noida5595@example.com",
    website: "https://uniformapp.in/genesis-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Genesis_Global_School_Noida_Noida_image1_161.jpeg",
  },
  {
    name: "Global Indian International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "276215",
    address: "Global Indian International School Noida, Noida",
    feesMin: 46134,
    feesMax: 49613,
    phone: "+918784479790",
    email: "global-indian-international-sc3637@example.com",
    website:
      "https://uniformapp.in/global-indian-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Global_Indian_International_School_Noida_Noida_image1_162.jpeg",
  },
  {
    name: "Green Valley Academy Noida",
    board: "State Board",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "140122",
    address: "Green Valley Academy Noida, Noida",
    feesMin: 44554,
    feesMax: 152053,
    phone: "+919292495975",
    email: "green-valley-academy-noida1803@example.com",
    website: "https://uniformapp.in/green-valley-academy-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/GREEN VALLEY ACADEMY 001.png",
  },
  {
    name: "Gyanshree School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "448414",
    address: "Noida Expressway",
    feesMin: 45676,
    feesMax: 118567,
    phone: "+916937098814",
    email: "gyanshree-school-noida1989@example.com",
    website: "https://uniformapp.in/gyanshree-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Gyanshree_School_Noida_Noida_image1_164.jpeg",
  },
  {
    name: "Indraprastha GLOBAL School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "491162",
    address: "Sector 62A",
    feesMin: 32454,
    feesMax: 34612,
    phone: "+919758871282",
    email: "indraprastha-global-school-noi9622@example.com",
    website: "https://uniformapp.in/indraprastha-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Indraprastha_GLOBAL_School_Noida_Noida_image1_165.jpeg",
  },
  {
    name: "Jagran Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "233516",
    address: "Sector 47",
    feesMin: 15860,
    feesMax: 49364,
    phone: "+918789773331",
    email: "jagran-public-school-noida3471@example.com",
    website: "https://uniformapp.in/jagran-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Jagran_Public_School_Noida_Noida_image1_166.jpeg",
  },
  {
    name: "Jaypee Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "865600",
    address: "Wish Town",
    feesMin: 42191,
    feesMax: 164743,
    phone: "+919985542290",
    email: "jaypee-public-school-noida4087@example.com",
    website: "https://uniformapp.in/jaypee-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Jaypee_Public_School_Noida_Noida_image1_167.jpeg",
  },
  {
    name: "JBM Global School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "264282",
    address: "Sector 132",
    feesMin: 15645,
    feesMax: 38913,
    phone: "+919506661405",
    email: "jbm-global-school-noida7100@example.com",
    website: "https://uniformapp.in/jbm-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/JBM_Global_School_Noida_Noida_image1_168.jpeg",
  },
  {
    name: "JSS Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "713210",
    address: "JSS Public School Noida, Noida",
    feesMin: 49818,
    feesMax: 142489,
    phone: "+919891856957",
    email: "jss-public-school-noida4456@example.com",
    website: "https://uniformapp.in/jss-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/JSS Public School A-104-a Behind Shopprix Mall Sec-61 Noida2.jpg",
  },
  {
    name: "Kothari International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "512172",
    address: "B Block, Sector 50",
    feesMin: 16849,
    feesMax: 105804,
    phone: "+918677587269",
    email: "kothari-international-school-n3478@example.com",
    website: "https://uniformapp.in/kothari-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Kothari_International_School_Noida_Noida_image1_170.jpeg",
  },
  {
    name: "Lord Mahavira School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "798591",
    address: "Sector-29",
    feesMin: 29370,
    feesMax: 45945,
    phone: "+917248333393",
    email: "lord-mahavira-school-noida9872@example.com",
    website: "https://uniformapp.in/lord-mahavira-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Lord_Mahavira_School_Noida_Noida_image1_171.jpeg",
  },
  {
    name: "LPS Global School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "301959",
    address: "Sector 51",
    feesMin: 8891,
    feesMax: 73769,
    phone: "+917354275787",
    email: "lps-global-school-noida4136@example.com",
    website: "https://uniformapp.in/lps-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/LPS_Global_School_Noida_Noida_image1_173.jpeg",
  },
  {
    name: "Maharishi Vidya Mandir School Noida",
    board: "State Board",
    medium: "Hindi",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "202919",
    address: "Sector 36",
    feesMin: 29824,
    feesMax: 44487,
    phone: "+918676262470",
    email: "maharishi-vidya-mandir-school-8599@example.com",
    website: "https://uniformapp.in/maharishi-vidya-mandir-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Maharishi_Vidya_Mandir_School_Noida_Noida_image1_174.jpeg",
  },
  {
    name: "Manav Rachna International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "665419",
    address: "Sector 51",
    feesMin: 26936,
    feesMax: 38552,
    phone: "+919620006817",
    email: "manav-rachna-international-sch9560@example.com",
    website:
      "https://uniformapp.in/manav-rachna-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Manav_Rachna_International_School_Noida_Noida_image1_175.jpeg",
  },
  {
    name: "Mayoor School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "550326",
    address: "Sector 126",
    feesMin: 6238,
    feesMax: 107321,
    phone: "+916965496333",
    email: "mayoor-school-noida1621@example.com",
    website: "https://uniformapp.in/mayoor-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Mayoor_School_Noida_Noida_image1_176.jpeg",
  },
  {
    name: "N.S Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "216447",
    address: "Gautam Budh Nagar",
    feesMin: 46266,
    feesMax: 139473,
    phone: "+919035111767",
    email: "n-s-public-school-noida3542@example.com",
    website: "https://uniformapp.in/ns-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/NS_Public_School_Noida_Noida_image1_177.jpeg",
  },
  {
    name: "Nilgiri Hills Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "834683",
    address: "Gautam Budh Nagar",
    feesMin: 35747,
    feesMax: 44396,
    phone: "+918668541925",
    email: "nilgiri-hills-public-school-no9250@example.com",
    website: "https://uniformapp.in/nilgiri-hills-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Nilgiri_Hills_Public_School_Noida_Noida_image1_178.jpeg",
  },
  {
    name: "Noida International Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "511320",
    address: "Noida International Public School Noida, Noida",
    feesMin: 22145,
    feesMax: 144241,
    phone: "+917301370566",
    email: "noida-international-public-sch1342@example.com",
    website:
      "https://uniformapp.in/noida-international-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Noida International Public School Garhi Chaukhandimp3 Main Road Sector-121 Noida5.jpg",
  },
  {
    name: "Noida Public Senior Secondary School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "303684",
    address: "Noida Public Senior Secondary School Noida, Noida",
    feesMin: 5263,
    feesMax: 57346,
    phone: "+916391397624",
    email: "noida-public-senior-secondary-5083@example.com",
    website:
      "https://uniformapp.in/noida-public-senior-secondary-school-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Om Shanti Om International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "523957",
    address: "Bassi Village",
    feesMin: 32030,
    feesMax: 114661,
    phone: "+919139252598",
    email: "om-shanti-om-international-sch5151@example.com",
    website:
      "https://uniformapp.in/om-shanti-om-international-school-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Panchsheel Balak Inter College Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "100552",
    address: "Gautam Budh Nagar",
    feesMin: 49285,
    feesMax: 160431,
    phone: "+919034079322",
    email: "panchsheel-balak-inter-college6684@example.com",
    website: "https://uniformapp.in/panchsheel-balak-inter-college-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Panchsheel_Balak_Inter_College_Noida_Noida_image1_182.jpeg",
  },
  {
    name: "Presidium School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "216047",
    address: "Presidium School Noida, Noida",
    feesMin: 44435,
    feesMax: 106865,
    phone: "+919569429601",
    email: "presidium-school-noida5410@example.com",
    website: "https://uniformapp.in/presidium-school-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Punchsheel Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "New",
    state: "Maharashtra",
    pinCode: "849451",
    address: "Punchsheel Public School Noida, New",
    feesMin: 22941,
    feesMax: 136154,
    phone: "+917982896730",
    email: "punchsheel-public-school-noida1801@example.com",
    website: "https://uniformapp.in/punchsheel-public-school-noida-new+delhi",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Raghav Global School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "728142",
    address: "Raghav Global School Noida, Noida",
    feesMin: 16135,
    feesMax: 64877,
    phone: "+916001948560",
    email: "raghav-global-school-noida6119@example.com",
    website: "https://uniformapp.in/raghav-global-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Raghav_Global_School_Noida_Noida_image1_186.jpeg",
  },
  {
    name: "RAMAGYA School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "209803",
    address: "Sector 50",
    feesMin: 47394,
    feesMax: 110483,
    phone: "+917968484354",
    email: "ramagya-school-noida3661@example.com",
    website: "https://uniformapp.in/ramagya-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/RAMAGYA_School_Noida_Noida_image1_187.jpeg",
  },
  {
    name: "REAL VIEW PUBLIC School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "New",
    state: "Karnataka",
    pinCode: "990796",
    address: "REAL VIEW PUBLIC School Noida, New",
    feesMin: 32638,
    feesMax: 138475,
    phone: "+917933662568",
    email: "real-view-public-school-noida2372@example.com",
    website: "https://uniformapp.in/real-view-public-school-noida-new+delhi",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "RockWood School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "380751",
    address: "Sector 33",
    feesMin: 36431,
    feesMax: 149822,
    phone: "+917833071720",
    email: "rockwood-school-noida168@example.com",
    website: "https://uniformapp.in/rockwood-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/RockWood_School_Noida_Noida_image1_191.jpeg",
  },
  {
    name: "Ryan International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "151279",
    address: "Ryan International School Noida, Noida",
    feesMin: 31466,
    feesMax: 81846,
    phone: "+916565724802",
    email: "ryan-international-school-noid3202@example.com",
    website: "https://uniformapp.in/ryan-international-school-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Shiv Nadar School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "699317",
    address: "Expressway",
    feesMin: 38415,
    feesMax: 97641,
    phone: "+917139325892",
    email: "shiv-nadar-school-noida9203@example.com",
    website: "https://uniformapp.in/shiv-nadar-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Shiv_Nadar_School_Noida_Noida_image1_195.jpeg",
  },
  {
    name: "Silvertone School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "675310",
    address: "Sector-47",
    feesMin: 13386,
    feesMax: 137566,
    phone: "+916940088153",
    email: "silvertone-school-noida9137@example.com",
    website: "https://uniformapp.in/silvertone-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Silvertone_School_Noida_Noida_image1_196.jpeg",
  },
  {
    name: "Somerville International School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "750793",
    address: "Sector 132",
    feesMin: 44384,
    feesMax: 168853,
    phone: "+918546188635",
    email: "somerville-international-schoo8953@example.com",
    website:
      "https://uniformapp.in/somerville-international-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Somerville_International_School_Noida_Noida_image1_197.jpeg",
  },
  {
    name: "Step by Step School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "520721",
    address: "Sector - 132",
    feesMin: 23553,
    feesMax: 71531,
    phone: "+919650136382",
    email: "step-by-step-school-noida2476@example.com",
    website: "https://uniformapp.in/step-by-step-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Step_by_Step_School_Noida_Noida_image1_198.jpeg",
  },

  {
    name: "Sunriseville School Noida",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "187852",
    address: "Sector 25",
    feesMin: 48284,
    feesMax: 60005,
    phone: "+918510360846",
    email: "sunriseville-school-noida5447@example.com",
    website: "https://uniformapp.in/sunriseville-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Sunriseville_School_Noida_Noida_image1_199.jpeg",
  },
  {
    name: "The Millennium School Sector 41 Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "581441",
    address: "Sector 41",
    feesMin: 11858,
    feesMax: 122106,
    phone: "+918324925915",
    email: "the-millennium-school-sector-42221@example.com",
    website:
      "https://uniformapp.in/the-millennium-school-sector-41-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/The_Millennium_School_Sector_41_Noida_Noida_image1_201.jpeg",
  },
  {
    name: "The Millennium School Sector 119 Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "643010",
    address: "Sector 119",
    feesMin: 24402,
    feesMax: 118792,
    phone: "+917806778307",
    email: "the-millennium-school-sector-17588@example.com",
    website:
      "https://uniformapp.in/the-millennium-school-sector-119-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "The SD Vidya School Noida",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "240808",
    address: "Sec- 49",
    feesMin: 40148,
    feesMax: 94293,
    phone: "+917781292883",
    email: "the-sd-vidya-school-noida1343@example.com",
    website: "https://uniformapp.in/the-sd-vidya-school-noida-noida",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.svg",
  },
  {
    name: "Vishwa Bharati Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "852601",
    address: "Gautam Budh Nagar",
    feesMin: 11860,
    feesMax: 121855,
    phone: "+916917745424",
    email: "vishwa-bharati-public-school-n4536@example.com",
    website: "https://uniformapp.in/vishwa-bharati-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Vishwa_Bharati_Public_School_Noida_Noida_image1_204.jpeg",
  },
  {
    name: "Yadu Public School Noida",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Noida",
    state: "Uttar Pradesh",
    pinCode: "208046",
    address: "Gautam Budh Nagar",
    feesMin: 15661,
    feesMax: 37639,
    phone: "+918608841773",
    email: "yadu-public-school-noida8666@example.com",
    website: "https://uniformapp.in/yadu-public-school-noida-noida",
    image:
      "https://uniformapp.in/admin_area/school_images/Yadu_Public_School_Noida_Noida_image1_205.jpeg",
  },
  {
    name: "Aakash Public School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "402670",
    address: "Aakash Public School, Gurgaon",
    feesMin: 11633,
    feesMax: 115431,
    phone: "+917416844754",
    email: "aakash-public-school6659@example.com",
    website: "https://uniformapp.in/aakash-public-school-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Aakash Public School Sector- 5 Community Centre Gurugram0.jpg",
  },
  {
    name: "Aarsha Public School",
    board: "State Board",
    medium: "Hindi",
    type: "Private",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "755917",
    address: "Aarsha Public School, Gurgaon",
    feesMin: 29347,
    feesMax: 70800,
    phone: "+919520076361",
    email: "aarsha-public-school5984@example.com",
    website: "https://uniformapp.in/aarsha-public-school-gurgaon",
    image: "https://uniformapp.in/admin_area/school_images/schoolnopic.jpg",
  },
  {
    name: "Air Force School",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "249526",
    address: "Air Force School, Gurgaon",
    feesMin: 49821,
    feesMax: 153352,
    phone: "+917355780169",
    email: "air-force-school9975@example.com",
    website: "https://uniformapp.in/air-force-school--gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Air Force School Old Delhi Road Gurugram0.jpg",
  },
  {
    name: "Ajanta Public School",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "163385",
    address: "Ajanta Public School, Gurgaon",
    feesMin: 28138,
    feesMax: 89563,
    phone: "+918876280956",
    email: "ajanta-public-school4484@example.com",
    website: "https://uniformapp.in/ajanta-public-school-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Ajanta Public School Sector - 31 Gurugram4.jpg",
  },
  {
    name: "Alpine Convent School Sec 38",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "767105",
    address: "Alpine Convent School Sec 38, Gurgaon",
    feesMin: 11344,
    feesMax: 130894,
    phone: "+919325187317",
    email: "alpine-convent-school-sec-386746@example.com",
    website: "https://uniformapp.in/alpine-convent-school-sec-38-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/ALPINE CONVENT SCHOOL Behind Jalvayu Towersblock Bsec-56 Gurugram1.jpg",
  },
  {
    name: "Alpine Convent School Sec 56",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "262039",
    address: "Sector 56",
    feesMin: 16582,
    feesMax: 37607,
    phone: "+918367637135",
    email: "alpine-convent-school-sec-561257@example.com",
    website: "https://uniformapp.in/alpine-convent-school-sec-56-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Alpine_Convent_School_Sec_56_Gurgaon_image1_211.jpeg",
  },
  {
    name: "Ambience Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "803030",
    address: "Ambience Public School, Gurgaon",
    feesMin: 44115,
    feesMax: 179953,
    phone: "+917026828036",
    email: "ambience-public-school7999@example.com",
    website: "https://uniformapp.in/ambience-public-school-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Ambience Public School Plot No 1 Sec 43 Gurugram3.jpg",
  },
  {
    name: "American Montessori Public School Junior Wing",
    board: "CBSE",
    medium: "English",
    type: "Private",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "411057",
    address: "American Montessori Public School Junior Wing, Gurgaon",
    feesMin: 17058,
    feesMax: 93908,
    phone: "+917562638109",
    email: "american-montessori-public-sch8907@example.com",
    website:
      "https://uniformapp.in/american-montessori-public-school-junior-wing-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/AMERICAN MONTESSORI PUBLIC SCHOOL JUINOR WING L-block Cassia Margdlf City Phase-ii Gurugram1.jpg",
  },
  {
    name: "American Montessori Public School Senior Wing",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "908897",
    address: "American Montessori Public School Senior Wing, Gurgaon",
    feesMin: 40359,
    feesMax: 130345,
    phone: "+918244460520",
    email: "american-montessori-public-sch6495@example.com",
    website:
      "https://uniformapp.in/american-montessori-public-school-senior-wing-gurgaon",
    image: "https://uniformapp.in/admin_area/school_images/americans.jpg",
  },
  {
    name: "Amity Global School Sec 46",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "181621",
    address: "Sector 46",
    feesMin: 41582,
    feesMax: 60063,
    phone: "+917766791699",
    email: "amity-global-school-sec-467696@example.com",
    website: "https://uniformapp.in/amity-global-school-sec-46-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_Global_School_Sec_46_Gurgaon_image1_215.jpeg",
  },
  {
    name: "Amity International School Sec 46",
    board: "CBSE",
    medium: "English",
    type: "Government",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "779581",
    address: "Vikas Marg",
    feesMin: 44545,
    feesMax: 82753,
    phone: "+917711614464",
    email: "amity-international-school-sec8983@example.com",
    website: "https://uniformapp.in/amity-international-school-sec-46-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_International_School_Sec_46_Gurgaon_image1_216.jpeg",
  },
  {
    name: "Amity International School Sec 43",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "750803",
    address: "Sector 43",
    feesMin: 41365,
    feesMax: 115339,
    phone: "+919277434532",
    email: "amity-international-school-sec8780@example.com",
    website: "https://uniformapp.in/amity-international-school-sec-43-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/Amity_International_School_Sec_43_Gurgaon_image1_217.jpeg",
  },
  {
    name: "Ascent Public School",
    board: "CBSE",
    medium: "English",
    type: "Aided",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "287161",
    address: "Ascent Public School, Gurgaon",
    feesMin: 12099,
    feesMax: 48690,
    phone: "+917153669529",
    email: "ascent-public-school9934@example.com",
    website: "https://uniformapp.in/ascent-public-school-gurgaon",
    image: "https://uniformapp.in/admin_area/school_images/ascentts.jpg",
  },
  {
    name: "Avr Public School",
    board: "CBSE",
    medium: "English",
    type: "Public",
    city: "Gurgaon",
    state: "Haryana",
    pinCode: "969542",
    address: "Avr Public School, Gurgaon",
    feesMin: 28830,
    feesMax: 140387,
    phone: "+919809729951",
    email: "avr-public-school6744@example.com",
    website: "https://uniformapp.in/avr-public-school-gurgaon",
    image:
      "https://uniformapp.in/admin_area/school_images/AVR Public School Rajiv Nagar Opp. Air Force Messsec-14 Gurugram3.jpg",
  },
];
